[package]
name = "essential-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.86"
essential-constraint-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-sign = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-hash = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-constraint-vm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-state-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-state-read-vm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
hex = "0.4.3"
inquire = "0.7.5"
serde_json = "1"
tokio = { version = "1.36", features = ["full"] }

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] } # For VM tests.
secp256k1 = { version = "0.29", features = ["recovery", "rand"] }